language: minimal
sudo: required
install:
  - wget https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip -O packer.zip
  - unzip packer.zip
  - mv packer /usr/bin
  - packer build templates/hello.json